# Generated by Codex on 2026-05-31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('text', models.TextField(verbose_name='Matn')),
                ('image_path', models.CharField(blank=True, max_length=300, null=True, verbose_name='Rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reklama',
                'verbose_name_plural': 'Reklamalar',
                'ordering': ['-id'],
            },
        ),
    ]
