# Generated by Django 6.0.4 on 2026-05-26 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_parent_category_type_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
    ]
