# Generated by Codex on 2026-05-31

from django.db import migrations, models


def copy_category_to_categories(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    db_alias = schema_editor.connection.alias
    for product in Product.objects.using(db_alias).exclude(category_id__isnull=True):
        product.categories.add(product.category_id)


def copy_categories_to_category(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    db_alias = schema_editor.connection.alias
    for product in Product.objects.using(db_alias).all():
        first_category = product.categories.first()
        if first_category:
            product.category_id = first_category.id
            product.save(update_fields=['category'])


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_name_search_product_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='categories.category'),
        ),
        migrations.RunPython(copy_category_to_categories, copy_categories_to_category),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
